# Generated by Django 5.2.1 on 2025-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='class',
            name='day_of_week',
            field=models.CharField(choices=[('MONDAY', '월요일'), ('TUESDAY', '화요일'), ('WEDNESDAY', '수요일'), ('THURSDAY', '목요일'), ('FRIDAY', '금요일'), ('SATURDAY', '토요일'), ('SUNDAY', '일요일')], max_length=10, verbose_name='요일'),
        ),
    ]
