# Generated by Django 5.2.1 on 2025-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_name_alter_class_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '관리자'), ('TEACHER', '선생님'), ('ASSISTANT', '조교')], max_length=10, verbose_name='권한'),
        ),
    ]
