# Generated by Django 5.2.1 on 2025-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.PositiveIntegerField(default=100, verbose_name='만점'),
        ),
    ]
