# Generated by Django 5.2.1 on 2025-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_exam_max_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.CharField(
                choices=[
                    ("REVIEW", "복습테스트"),
                    ("ESSAY", "서술테스트"),
                    ("ORAL", "구술테스트"),
                    ("MOCK", "모의고사"),
                    ("SCHOOL", "학교기출"),
                ],
                default="REVIEW",
                max_length=10,
                verbose_name="시험종류",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A", "A"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B", "B"),
                    ("B-", "B-"),
                    ("C+", "C+"),
                    ("C", "C"),
                    ("C-", "C-"),
                    ("D", "D"),
                    ("F", "F"),
                ],
                max_length=2,
                null=True,
                verbose_name="등급",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="max_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="만점"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="점수"
            ),
        ),
    ]
