# Generated by Django 5.2.1 on 2025-12-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_exam_category_exam_grade_alter_exam_max_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_info",
        ),
        migrations.AddField(
            model_name="attendance",
            name="class_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.class",
                verbose_name="반",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes",
                to="students.student",
                verbose_name="학생들",
            ),
        ),
    ]
