# Generated by Django 5.2.1 on 2026-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_remove_student_class_info_attendance_class_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="학교"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("name", "parent_phone"), name="unique_student_parent_phone"
            ),
        ),
    ]
