# Generated by Django 5.2.1 on 2026-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_school_student_unique_student_parent_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONDAY", "월요일"),
                    ("TUESDAY", "화요일"),
                    ("WEDNESDAY", "수요일"),
                    ("THURSDAY", "목요일"),
                    ("FRIDAY", "금요일"),
                    ("SATURDAY", "토요일"),
                    ("SUNDAY", "일요일"),
                ],
                max_length=10,
                null=True,
                verbose_name="요일",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="수업 시작시간"),
        ),
        migrations.AlterField(
            model_name="class",
            name="subject",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEMISTRY", "화학"),
                    ("BIOLOGY", "생명"),
                    ("GEOSCIENCE", "지학"),
                ],
                max_length=20,
                null=True,
                verbose_name="과목",
            ),
        ),
    ]
