# Generated by Django 5.2.1 on 2026-03-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_add_subject_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="old_subject",
        ),
        migrations.RemoveField(
            model_name="user",
            name="old_subject",
        ),
    ]
