# Generated by Django 5.2.1 on 2026-04-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_cleanup_old_subject_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="students.subject",
                verbose_name="과목",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="max_score",
            field=models.FloatField(blank=True, null=True, verbose_name="만점"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="점수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="students.subject",
                verbose_name="권한 과목",
            ),
        ),
    ]
